version: '2'
services:
  zabbix-agent:
    image: monitoringartist/dockbix-agent-xxl-limited:3.4-3
    privileged: true
    network_mode: "host"
    volumes:
      - /:/rootfs
      - /var/run:/var/run
    restart: unless-stopped
    environment:
      - ZA_Server=::/0,0.0.0.0/0,${zabbix_server}
      - ZA_ServerActive=${zabbix_server}
    labels:
      io.rancher.scheduler.global: 'true'